# Generated by Django 5.2 on 2025-05-27 02:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('interprete', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('derechos', models.CharField(max_length=200)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
    ]
