# Generated by Django 5.2 on 2025-05-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='derechos',
            new_name='derechos_autor',
        ),
    ]
