# Generated by Django 5.2 on 2025-05-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_rename_derechos_audio_derechos_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='compositor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
