# Generated by Django 5.2 on 2025-06-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_audio_compositor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['genero']},
        ),
        migrations.AlterField(
            model_name='audio',
            name='derechos_autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='genero',
            field=models.CharField(max_length=100),
        ),
    ]
